### ISSUE TITLE
Addin Trait to method passing the parameters

### ISSUE THREAD

**Issue by eliasmamo** [mulesoft/raml-object-to-raml#7]
I am trying to add an "is" statement with reference to a trait and pass parameters. Currently have no reference how to do that, the best result i was able to get is: 

```
get:
    is:
      - 2222:
          VarName1: varParam1
          VarName2: varParam2
```

in RAML docs it should look like

```
get:
    is: [ 2222: { VarName1: varParam1,  VarName2: varParam2} ]
```

i didn't find any tests for this functionality, there is only one test where trait is simply referenced by name.
